---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  tasks:
    - name: Initialize the Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_output
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to userâ€™s kube config
      command: cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config

    - name: Change ownership of kube config
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu

    - name: Install Calico network plugin
      become_user: ubuntu
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command_output

    - name: Save join command to file
      copy:
        content: "{{ join_command_output.stdout }}"
        dest: /home/ubuntu/join_command.sh
